-- Dynamically find Mason's installation path
local mason_bin = vim.fn.stdpath("data") .. "/mason/bin/"
-- On Windows, adjust path separator and extension if necessary:
if vim.fn.has("win32") == 1 then
  mason_bin = mason_bin:gsub("/", "\\")
end

vim.lsp.config['clangd'] = {
  cmd = {
    mason_bin .. 'clangd',
    '--background-index',       -- Index codebase in background
    '--clang-tidy',             -- Enable inline linter diagnostics
    '--header-insertion=iwyu',  -- Auto-insert missing includes ("Include What You Use")
    '--completion-style=detailed',
    '--fallback-style=llvm',
  },
  filetypes = { 'c', 'cpp', 'objc', 'objcpp' },
  root_markers = {
    'compile_commands.json',    -- Standard compilation DB generated by CMake/Bear
    'compile_flags.txt',
    '.clangd',
    '.git',
  },
}

vim.lsp.enable('clangd')

