config_version = 8

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-6",
    "lockscreen-login-box@DP-4",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001"
]

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "ghostty", "hyprland", "kitty" ]

[wallpaper]
directory = "/home/patrykwisniewski/Vault/Notes/Wallpappers"

    [wallpaper.default]
    path = "/home/patrykwisniewski/Vault/Notes/Wallpappers/london-night-river.jpg"

    [wallpaper.last]
    path = "/home/patrykwisniewski/Vault/Notes/Wallpappers/london-night-river.jpg"

    [wallpaper.monitors.DP-4]
    path = "/home/patrykwisniewski/Vault/Notes/Wallpappers/london-night-river.jpg"

    [wallpaper.monitors.DP-6]
    path = "/home/patrykwisniewski/Vault/Notes/Wallpappers/london-night-river.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/patrykwisniewski/Vault/Notes/Wallpappers/london-night-river.jpg"