
# better prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on

