[Login]
#SleepOperation=suspend-then-hibernate suspend
#HandlePowerKey=poweroff
#HandlePowerKeyLongPress=ignore
#HandleRebootKey=reboot
#HandleRebootKeyLongPress=poweroff
#HandleSuspendKey=suspend
#HandleSuspendKeyLongPress=hibernate
#HandleHibernateKey=hibernate
#HandleHibernateKeyLongPress=ignore
#HandleLidSwitch=suspend => default
HandleLidSwitch=ignore
#HandleLidSwitchExternalPower=suspend => default
HandleLidSwitchExternalPower=ignore
#HandleLidSwitchDocked=ignore
#HandleSecureAttentionKey=secure-attention-key
#For hardware button or lid actions, valid targets include ignore, lock, suspend, hibernate, poweroff, or reboot
